name: deploy

on:
  push:
    branches:
      - deploy # deploy 브랜치에서 push 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-deploy-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          CI: ""

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_FRONT_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_FRONT_SECRET_KEY }}
        run: |
          aws s3 cp build/\
            --recursive \
            --region ap-northeast-2 \
            dist s3://facereview-front
